# DX 601 Week 9 Homework

## Introduction

In this homework, you will practice basic operations with vectors and matrices.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [2]:
import math
import sys

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Problems

### Problem 1

Set `p1` to the vector from calculating $[0.0, 0.3, 0.65] + [2.2, 6.2, 0.35]$.

In [59]:
# YOUR CHANGES HERE

p1 = [2.2, 6.5, 1]

In [60]:
p1

[2.2, 6.5, 1]

### Problem 2

Set `p2` to the magnitude of the vector $[1, 3, 6]$?

In [65]:
# YOUR CHANGES HERE

vec = [1, 3, 6]

vec_sq = [x ** 2 for x in vec]

p2 = math.sqrt(sum(vec_sq))

In [66]:
p2

6.782329983125268

### Problem 3

Set `p3` to the magnitude of the vector `q3`.

In [8]:
# DO NOT CHANGE

q3 = np.asarray([5.2, 5.9, 9.1, 4.3, 2.9])
q3

array([5.2, 5.9, 9.1, 4.3, 2.9])

In [69]:
# YOUR CHANGES HERE

q3_sq = [x ** 2 for x in q3]

p3 = math.sqrt(sum(q3_sq))

In [70]:
p3

13.098091464026353

### Problem 4

Set `p4` to the dot product of $[2, 0, 3]$ and $[0, 4, 1]$.

Hint: this should feel like a really easy case to just do in your head.

In [72]:
# YOUR CHANGES HERE
dp = []
v1 = [2, 0, 3]
v2 = [0, 4, 1]

for i in range(len(v1)):
    dp.append(v1[i] * v2[i])

p4 = sum(dp)

In [73]:
p4

3

### Problem 5

Set `p5` to the element-wise product of `u5` and `v5`.

Hint: the default behavior of mathematical operations on NumPy arrays is to calculate on an element-wise basis.

In [13]:
# DO NOT CHANGE

u5 = np.asarray([5, 5, 5])
u5

array([5, 5, 5])

In [14]:
# DO NOT CHANGE

v5 = np.asarray([1, 6, 2])
v5

array([1, 6, 2])

In [74]:
# YOUR CHANGES HERE

p5 = u5 * v5

In [75]:
p5

array([ 5, 30, 10])

### Problem 6

Set `p6` to the dot product of `u6` and `v6`.

In [17]:
# DO NOT CHANGE

u6 = np.asarray([2.03, 0.40, 1.35, 9.26, 4.23])
u6

array([2.03, 0.4 , 1.35, 9.26, 4.23])

In [18]:
# DO NOT CHANGE

v6 = np.asarray([1.32, 0.96, 2.35, 1.23, 0.25])
v6

array([1.32, 0.96, 2.35, 1.23, 0.25])

In [76]:
# YOUR CHANGES HERE

dp = []

for i in range(len(u6)):
    dp.append(u6[i] * v6[i])

p6 = sum(dp)

In [77]:
p6

np.float64(18.683400000000002)

### Problem 7

Set `p7` to the cosine similarity of `u7` and `v7`.

In [21]:
# DO NOT CHANGE

u7 = np.asarray([1, 1, 1, 1])
u7

array([1, 1, 1, 1])

In [22]:
# DO NOT CHANGE

v7 = np.asarray([0, 2, 0, 0])
v7

array([0, 2, 0, 0])

In [83]:
# YOUR CHANGES HERE

dp = []

for i in range(len(u7)):
    dp.append(u7[i] * v7[i])

dp = sum(dp)

mag1 = math.sqrt(sum(u7 ** 2))
mag2 = math.sqrt(sum(v7 ** 2))

p7 = dp/(mag1 * mag2)

In [84]:
p7

np.float64(0.5)

### Problem 8

Set `p8` to the vector $[x, y]$ corresponding to the polar coordinates $(r, \theta) = (1, 1)$.

In [86]:
# YOUR CHANGES HERE

p8 = [1 * math.cos(1), 1 * math.sin(1)]

In [87]:
p8

[0.5403023058681398, 0.8414709848078965]

### Problem 9

Set `p9` to the scalar-vector product $3.1 \cdot [1.31, 2.06, 9.56, 1.79]$.

In [90]:
# YOUR CHANGES HERE

p9 = 3.1 * np.array([1.31, 2.06, 9.56, 1.79])

In [91]:
p9

array([ 4.061,  6.386, 29.636,  5.549])

### Problem 10

Set `p10` to be a unit vector in the same direction as $[1.31, 2.13, -0.92]$.


In [92]:
# YOUR CHANGES HERE

vec = np.array([1.31, 2.13, -0.92])

mag = math.sqrt(sum(vec**2))

uv = []

for i in range(len(vec)):
    uv.append(vec[i]/mag)

p10 = uv

In [93]:
p10

[np.float64(0.4916550139961552),
 np.float64(0.7994085342074889),
 np.float64(-0.3452844373102769)]

### Problem 11

Set `p11` to be the first of the following vectors that is orthogonal to $[1, 0, 0]$.

* $[1, 1, 1]$
* $[0.5, 1, 1]$
* $[0, 1, 1]$
* $[1, 0, 1]$

In [96]:
p11 = [0, 1, 1]

In [97]:
p11

[0, 1, 1]

### Problem 12

Set `p12` to the first vector in the following list which is linearly dependent on the previous vectors.

* $[0, 1, 1]$
* $[0, 0, 1]$
* $[1, 0, 1]$
* $[1, 1, 1]$

In [98]:
# YOUR CHANGES HERE

p12 = [1, 1, 1]

In [99]:
p12

[1, 1, 1]

### Problem 13

Set `p13` to the $3 \times 3$ identity matrix.

In [103]:
# YOUR CHANGES HERE

p13 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [104]:
p13

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Problem 14

Set `p14` to the x intercept of the equation $3y + 5x = 2$.

In [105]:
# YOUR CHANGES HERE

p14 = 0.4

In [106]:
p14

0.4

### Problem 15

Given the dictionary of phrases and vectors in `q15`, set `p15` to the phrase (key) whose vector has the highest cosine similarity with $[0.1, 0.5, 0.2]$.

In [39]:
# DO NOT CHANGE

q15 = {
    "cat": [0.1, 0.6, 0.3],
    "dog": [0.2, 0.5, 0.1],
    "elephant": [-0.3, 0.2, 0.5],
    "giraffe": [-0.4, 0.3, -0.1],
    "lion": [0.1, 0.7, 0.2]
}
q15 = {k: np.asarray(v) for k, v in q15.items()}

q15

{'cat': array([0.1, 0.6, 0.3]),
 'dog': array([0.2, 0.5, 0.1]),
 'elephant': array([-0.3,  0.2,  0.5]),
 'giraffe': array([-0.4,  0.3, -0.1]),
 'lion': array([0.1, 0.7, 0.2])}

In [110]:
# YOUR CHANGES HERE

p15 = 'cat'

In [111]:
p15

'cat'

### Problem 16

Rescale the vectors $[2, 0, 0, 0]$ and $[0, 1, 1, 1]$ so that they are orthonormal.

Save the first rescaled vector in `p16a` and the second rescaled vector in `p16b`.

In [114]:
# YOUR CHANGES HERE

v1 = np.array([2, 0, 0, 0])
mag1 = math.sqrt(sum(v1 ** 2))

p16a = v1/mag1

In [115]:
p16a

array([1., 0., 0., 0.])

In [116]:
# YOUR CHANGES HERE

v2 = np.array([0, 1, 1, 1])
mag2 = math.sqrt(sum(v2 ** 2))

p16b = v2/mag2

In [117]:
p16b

array([0.        , 0.57735027, 0.57735027, 0.57735027])

### Problem 17

Set `p17` to the result of the matrix multiplication of `x17` by `y17`.

Hint: NumPy has a function for matrix multiplication, and also overrides the Python @ operator.

In [119]:
# DO NOT CHANGE

x17 = np.array([[0.2, 3.1, 0.6], [-2.9, 2.3, 4.2], [3.0, 4.5, 1.7]])
x17

array([[ 0.2,  3.1,  0.6],
       [-2.9,  2.3,  4.2],
       [ 3. ,  4.5,  1.7]])

In [120]:
# DO NOT CHANGE

y17 = np.array([[1, 2, 3], [6, 5, 4], [7, 8, 9]])
y17

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]])

In [121]:
# YOUR CHANGES HERE

p17 = np.matmul(x17, y17)

In [122]:
p17

array([[23. , 20.7, 18.4],
       [40.3, 39.3, 38.3],
       [41.9, 42.1, 42.3]])

### Problem 18

Set `p18` to the angle $\theta$ between the vectors in `u18` and `v18`.
Use the measure of the angle in radians, not degrees.

Hint: you can use the cosine similarity to calculate $\mathrm{cos}~\theta$.
The inverse cosine function to recover the measure of the angle is often called the arc cosine, and both the math and NumPy modules use this for their naming.

In [50]:
# DO NOT CHANGE

u18 = np.asarray([0.3, 0.2, 0.9, -0.4])
u18

array([ 0.3,  0.2,  0.9, -0.4])

In [51]:
# DO NOT CHANGE

v18 = np.asarray([-0.1, 0.3, 0.6, -0.2])
v18

array([-0.1,  0.3,  0.6, -0.2])

In [123]:
# YOUR CHANGES HERE

mag1 = math.sqrt(sum(u18 ** 2))
mag2 = math.sqrt(sum(v18 ** 2))

csim = sum(u18 * v18)/(mag1 * mag2)

p18 = np.arccos(csim)

In [124]:
p18

np.float64(0.5023368499123664)

### Problem 19

Set `p19` to be the largest magnitude vector from the following list.

* $[0.1, 0.3, 0.9, -0.8]$
* $[0.2, 0.2, 0.7, 0.6]$
* $[-0.2, 0.2, 0.7, -0.6]$
* $[1.0, 1.0, 0.4, 0.5]$

In [126]:
# YOUR CHANGES HERE

p19 = np.array([1.0, 1.0, 0.4, 0.5])

In [127]:
p19

array([1. , 1. , 0.4, 0.5])

### Problem 20

Set `p20` to $3 \mathbf{x} + 5$ where $x$ is stored in `x20`.

In [128]:
# DO NOT CHANGE

x20 = np.asarray([0.2, 0.5, -0.3, 0.8])

In [129]:
# YOUR CHANGES HERE

p20 = np.array([3 * x + 5 for x in x20])

In [130]:
p20

array([5.6, 6.5, 4.1, 7.4])

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR ANSWER HERE